### PR TITLE
Add regional domains

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
Updates to `map_tools.py` and `create_maps.py` to add new regional domains.

### CODE REVIEW

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me.

**Review by CoryMartin-NOAA — COMMENTED** [review]
@kevindougherty-noaa everything looks good, but what about adding a couple other tests for some new domains? Not saying all 15, but maybe pick 1-2 at "random" to make sure they work?

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA I am actually thinking about it right now, I'm not sure if all or any will be good without the cartopy cfeatures. The coastlines and states automatically decrease the resolution size based on the domain. Since only the GSHHS is what works, this may need to be delayed until we get all those shape files figured out into this repository.

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa do the cartopy features work in the CI? is it just a hera problem?

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
