### PR TITLE
Creating Documentation for EMCPy using Sphinx

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
The following PR is to create a documentation webpage created by Sphinx. This will be a large PR with a lot of `.rst` and `.md` files to create the documentation as well as the following `html` that is created with Sphinx. Some code changes will also need to be implemented to utilize the sphinx-gallery plug in. These code changes will mainly be included in the `emcpy/examples` directory.

These changes were tested on a fork and were found to successfully produce a webpage with the documentation. The documentation is still a work in progress, but all the heavy lifting of creating the webpage is done in this PR.

### CODE REVIEW

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa how about a commit that removes that "&& ..." stuff just to ensure the website is updated properly, then a commit to put it back? This can wait until Tuesday if needed.

**Comment by CoryMartin-NOAA** [comment]
hmm, @kevindougherty-noaa that push didn't seem to run the new CI action/deploy the documentation...

**Comment by CoryMartin-NOAA** [comment]
I wonder if it is because it is on a fork, it pushes/deploys to your page still. If that's the case, then we probably just need to merge it in like it was at [a852928](https://github.com/NOAA-EMC/emcpy/pull/127/commits/a8529287f86a5083b8adb0e8e8eab0159bbb250c) and fix later if necessary

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA yes, I think that it is because it is on the fork. I'll change it back and we can set it up accordingly.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
