### PR TITLE
Bugfix/2d map scatter

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
Addresses Issue #115. There was a missing 'colorbar' in the skipvars that was being read into `ax.scatter()` which was kicking back an error when trying to create a 2d scatter map plot.  

Also removed map plotting classes that were still included in `plots.py` that should not have been there.

### CODE REVIEW

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA @aerorahul I assume something needs to be updated in `setup.py`, but would like if you took a look at it first before I start trying to update things.

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa why did this change... seems odd but it looks like proj is not being included and thus failing when it tries to install it... weird

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA I am not positive as to why it changed either. I only made changes to plotting source code.

**Comment by aerorahul** [comment]
I think this is an issue in the runners.  Everytime github updates the runners, we run into these issues.  I'll try and create a branch to figure this out, but it will take time.

**Comment by CoryMartin-NOAA** [comment]
In fact: https://github.com/NOAA-EMC/emcpy/actions/runs/3998512742/jobs/6900438342
I reran a previous PR's test and it fails now. So it's definitely a CI issue. EVA will have the same issue now too.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
