### PR TITLE
Add box and whisker plot capability

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
As requested, here is a box and whisker plot addition. The test produces the following figure:

image

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
Nice!

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa any reason why this is a draft PR?

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA it's automatically set to that, and forgot to hit ready for review.

**Review by EdwardSafford-NOAA — APPROVED** [review]
I like it!

**Pull request merged**
