### PR TITLE
Add NOAA and NWS logos

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
Grabbed transparent background images of the NOAA and NWS logos that can be added to a plot., which will be done in a future PR (addresses #46).

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
I don't think this is correct? it looks like they are like HTML or something?

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA That's what I thought as well but I wasn't sure. I tried `wget` and the url from just the image. I'll try again.

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa it looks like it grabbed some webpage or something instead, as I think PNGs should be rendered in GitHub if they are properly added.

**Comment by CoryMartin-NOAA** [comment]
> @kevindougherty-noaa it looks like it grabbed some webpage or something instead, as I think PNGs should be rendered in GitHub if they are properly added.

To verify the proper file was downloaded, on hera run `display file.png` and it should pop up with the image

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
